import { PrismaClient, SectionType, StickerType } from "@prisma/client";

const prisma = new PrismaClient();

interface TeamData {
  code: string;
  name: string;
  flag: string;
  confederation: string;
  players: string[];
}

const INTRO_STICKERS = [
  { name: "Portada del Álbum", type: StickerType.INTRO },
  { name: "Copa del Mundo FIFA", type: StickerType.INTRO },
  { name: "Logo FIFA World Cup 2026", type: StickerType.INTRO },
  { name: "Países Sede", type: StickerType.INTRO },
  { name: "Estados Unidos 🇺🇸", type: StickerType.INTRO },
  { name: "Canadá 🇨🇦", type: StickerType.INTRO },
  { name: "México 🇲🇽", type: StickerType.INTRO },
  { name: "Mascota Oficial", type: StickerType.INTRO },
  { name: "Historia del Mundial", type: StickerType.INTRO },
  { name: "Campeones Históricos", type: StickerType.INTRO },
];

const VENUE_STICKERS = [
  { name: "MetLife Stadium - New York", type: StickerType.STADIUM },
  { name: "SoFi Stadium - Los Angeles", type: StickerType.STADIUM },
  { name: "AT&T Stadium - Dallas", type: StickerType.STADIUM },
  { name: "Levi's Stadium - San Francisco", type: StickerType.STADIUM },
  { name: "Arrowhead Stadium - Kansas City", type: StickerType.STADIUM },
  { name: "Seahawks Stadium - Seattle", type: StickerType.STADIUM },
  { name: "Lincoln Financial Field - Filadelfia", type: StickerType.STADIUM },
  { name: "Hard Rock Stadium - Miami", type: StickerType.STADIUM },
  { name: "NRG Stadium - Houston", type: StickerType.STADIUM },
  { name: "Gillette Stadium - Boston", type: StickerType.STADIUM },
  { name: "BC Place - Vancouver", type: StickerType.STADIUM },
  { name: "BMO Field - Toronto", type: StickerType.STADIUM },
  { name: "Estadio Azteca - Ciudad de México", type: StickerType.STADIUM },
  { name: "Estadio BBVA - Monterrey", type: StickerType.STADIUM },
  { name: "Estadio Akron - Guadalajara", type: StickerType.STADIUM },
  { name: "Estadio Ciudad de los Deportes - CDMX", type: StickerType.STADIUM },
];

const TEAMS: TeamData[] = [
  // CONMEBOL
  {
    code: "ARG",
    name: "Argentina",
    flag: "🇦🇷",
    confederation: "CONMEBOL",
    players: [
      "Lionel Messi",
      "Emiliano Martínez",
      "Nahuel Molina",
      "Cristian Romero",
      "Lisandro Martínez",
      "Nicolás Tagliafico",
      "Rodrigo De Paul",
      "Leandro Paredes",
      "Enzo Fernández",
      "Alexis Mac Allister",
      "Lautaro Martínez",
      "Julián Álvarez",
      "Ángel Di María",
      "Paulo Dybala",
      "Giovani Lo Celso",
      "Germán Pezzella",
      "Thiago Almada",
      "Valentín Castellanos",
    ],
  },
  {
    code: "BRA",
    name: "Brasil",
    flag: "🇧🇷",
    confederation: "CONMEBOL",
    players: [
      "Alisson Becker",
      "Ederson",
      "Danilo",
      "Marquinhos",
      "Gabriel Magalhães",
      "Alex Telles",
      "Casemiro",
      "Bruno Guimarães",
      "Lucas Paquetá",
      "Vinícius Júnior",
      "Rodrygo",
      "Raphinha",
      "Richarlison",
      "Gabriel Martinelli",
      "Endrick",
      "Militão",
      "Gerson",
      "Savinho",
    ],
  },
  {
    code: "URU",
    name: "Uruguay",
    flag: "🇺🇾",
    confederation: "CONMEBOL",
    players: [
      "Sergio Rochet",
      "José María Giménez",
      "Ronald Araújo",
      "Mathías Olivera",
      "Rodrigo Bentancur",
      "Federico Valverde",
      "Matías Vecino",
      "Darwin Núñez",
      "Facundo Torres",
      "Nicolás de la Cruz",
      "Maximiliano Araújo",
      "Agustín Canobbio",
      "Sebastián Cáceres",
      "Lucas Torreira",
      "Diego Godín",
      "Nahitan Nández",
      "Brian Rodríguez",
      "Gastón Pereiro",
    ],
  },
  {
    code: "COL",
    name: "Colombia",
    flag: "🇨🇴",
    confederation: "CONMEBOL",
    players: [
      "David Ospina",
      "Davinson Sánchez",
      "Yerry Mina",
      "Johan Mojica",
      "Wilmar Barrios",
      "Juan Cuadrado",
      "James Rodríguez",
      "Mateus Uribe",
      "Luis Díaz",
      "Jhon Durán",
      "Rafael Santos Borré",
      "Radamel Falcao",
      "Alfredo Morelos",
      "Jorge Carrascal",
      "Óscar Murillo",
      "Daniel Muñoz",
      "Sebastián Villa",
      "Cucho Hernández",
    ],
  },
  {
    code: "ECU",
    name: "Ecuador",
    flag: "🇪🇨",
    confederation: "CONMEBOL",
    players: [
      "Hernán Galíndez",
      "Piero Hincapié",
      "Robert Arboleda",
      "Pervis Estupiñán",
      "Carlos Gruezo",
      "Moisés Caicedo",
      "Ángel Mena",
      "Gonzalo Plata",
      "Enner Valencia",
      "Jordy Caicedo",
      "Djorkaeff Reasco",
      "Ángel Preciado",
      "Alan Minda",
      "Antonio Valencia",
      "Junior Sornoza",
      "Michael Estrada",
      "Jeremy Sarmiento",
      "Félix Torres",
    ],
  },
  {
    code: "VEN",
    name: "Venezuela",
    flag: "🇻🇪",
    confederation: "CONMEBOL",
    players: [
      "Wuilker Faríñez",
      "Yordan Osorio",
      "Miguel Navarro",
      "Nahuel Ferraresi",
      "Tomás Rincón",
      "Yangel Herrera",
      "Darwin Machís",
      "Salomón Rondón",
      "Josef Martínez",
      "Rómulo Otero",
      "Christian Cásseres Jr.",
      "Adalberto Peñaranda",
      "Jefferson Savarino",
      "Jan Hurtado",
      "Eric Ramírez",
      "Yeferson Soteldo",
      "Junior Moreno",
      "Léo Fernández",
    ],
  },
  // UEFA
  {
    code: "ESP",
    name: "España",
    flag: "🇪🇸",
    confederation: "UEFA",
    players: [
      "Unai Simón",
      "David Raya",
      "Dani Carvajal",
      "Aymeric Laporte",
      "Pau Cubarsí",
      "Marc Cucurella",
      "Pedri",
      "Rodri",
      "Fabián Ruiz",
      "Yamal",
      "Álvaro Morata",
      "Ferran Torres",
      "Mikel Oyarzabal",
      "Dani Olmo",
      "Martín Zubimendi",
      "Mikel Merino",
      "Gavi",
      "Joselu",
    ],
  },
  {
    code: "FRA",
    name: "Francia",
    flag: "🇫🇷",
    confederation: "UEFA",
    players: [
      "Mike Maignan",
      "Jules Koundé",
      "William Saliba",
      "Ibrahima Konaté",
      "Theo Hernández",
      "N'Golo Kanté",
      "Aurélien Tchouaméni",
      "Antoine Griezmann",
      "Kylian Mbappé",
      "Ousmane Dembélé",
      "Marcus Thuram",
      "Randal Kolo Muani",
      "Benjamin Pavard",
      "Adrien Rabiot",
      "Eduardo Camavinga",
      "Kingsley Coman",
      "Christopher Nkunku",
      "Olivier Giroud",
    ],
  },
  {
    code: "ENG",
    name: "Inglaterra",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    confederation: "UEFA",
    players: [
      "Jordan Pickford",
      "Kyle Walker",
      "John Stones",
      "Marc Guéhi",
      "Luke Shaw",
      "Jude Bellingham",
      "Declan Rice",
      "Phil Foden",
      "Harry Kane",
      "Bukayo Saka",
      "Raheem Sterling",
      "Marcus Rashford",
      "Jack Grealish",
      "Trent Alexander-Arnold",
      "Conor Gallagher",
      "Cole Palmer",
      "Jarrod Bowen",
      "Anthony Gordon",
    ],
  },
  {
    code: "GER",
    name: "Alemania",
    flag: "🇩🇪",
    confederation: "UEFA",
    players: [
      "Manuel Neuer",
      "Benjamin Pavard",
      "Antonio Rüdiger",
      "Nico Schlotterbeck",
      "David Raum",
      "Joshua Kimmich",
      "Toni Kroos",
      "Leroy Sané",
      "Thomas Müller",
      "Kai Havertz",
      "Florian Wirtz",
      "Jamal Musiala",
      "İlkay Gündoğan",
      "Serge Gnabry",
      "Leon Goretzka",
      "Niclas Füllkrug",
      "Deniz Undav",
      "Chris Führich",
    ],
  },
  {
    code: "POR",
    name: "Portugal",
    flag: "🇵🇹",
    confederation: "UEFA",
    players: [
      "Diogo Costa",
      "João Cancelo",
      "Rúben Dias",
      "Pepe",
      "Nuno Mendes",
      "Bruno Fernandes",
      "Vitinha",
      "João Palhinha",
      "Cristiano Ronaldo",
      "Rafael Leão",
      "Pedro Neto",
      "Bernardo Silva",
      "Gonçalo Ramos",
      "Diogo Jota",
      "Otávio",
      "João Félix",
      "Rúben Neves",
      "Matheus Nunes",
    ],
  },
  {
    code: "NED",
    name: "Países Bajos",
    flag: "🇳🇱",
    confederation: "UEFA",
    players: [
      "Bart Verbruggen",
      "Denzel Dumfries",
      "Virgil van Dijk",
      "Stefan de Vrij",
      "Nathan Aké",
      "Frenkie de Jong",
      "Tijjani Reijnders",
      "Xavi Simons",
      "Memphis Depay",
      "Cody Gakpo",
      "Donyell Malen",
      "Steven Bergwijn",
      "Teun Koopmeiners",
      "Wout Weghorst",
      "Ryan Gravenberch",
      "Jeremie Frimpong",
      "Joshua Zirkzee",
      "Brian Brobbey",
    ],
  },
  {
    code: "BEL",
    name: "Bélgica",
    flag: "🇧🇪",
    confederation: "UEFA",
    players: [
      "Thibaut Courtois",
      "Thomas Meunier",
      "Toby Alderweireld",
      "Jan Vertonghen",
      "Leander Dendoncker",
      "Kevin De Bruyne",
      "Axel Witsel",
      "Youri Tielemans",
      "Eden Hazard",
      "Romelu Lukaku",
      "Lois Openda",
      "Jeremy Doku",
      "Dodi Lukebakio",
      "Amadou Onana",
      "Charles De Ketelaere",
      "Arthur Theate",
      "Johan Bakayoko",
      "Loïs Openda",
    ],
  },
  {
    code: "ITA",
    name: "Italia",
    flag: "🇮🇹",
    confederation: "UEFA",
    players: [
      "Gianluigi Donnarumma",
      "Giovanni Di Lorenzo",
      "Giorgio Scalvini",
      "Alessandro Buongiorno",
      "Federico Dimarco",
      "Nicolo Barella",
      "Jorginho",
      "Lorenzo Pellegrini",
      "Federico Chiesa",
      "Giacomo Raspadori",
      "Matteo Retegui",
      "Khvicha Kvaratskhelia",
      "Davide Frattesi",
      "Marco Verratti",
      "Leonardo Bonucci",
      "Sandro Tonali",
      "Samuele Ricci",
      "Luca Pellegrini",
    ],
  },
  {
    code: "CRO",
    name: "Croacia",
    flag: "🇭🇷",
    confederation: "UEFA",
    players: [
      "Dominik Livaković",
      "Josip Juranović",
      "Duje Ćaleta-Car",
      "Domagoj Vida",
      "Borna Sosa",
      "Luka Modrić",
      "Mateo Kovačić",
      "Marcelo Brozović",
      "Ivan Perišić",
      "Andrej Kramarić",
      "Bruno Petković",
      "Nikola Vlašić",
      "Lovro Majer",
      "Joško Gvardiol",
      "Mario Pašalić",
      "Sime Vrsaljko",
      "Ante Budimir",
      "Luka Ivanušec",
    ],
  },
  {
    code: "SRB",
    name: "Serbia",
    flag: "🇷🇸",
    confederation: "UEFA",
    players: [
      "Vanja Milinković-Savić",
      "Nemanja Gudelj",
      "Nikola Milenković",
      "Strahinja Pavlović",
      "Srđan Babić",
      "Saša Lukić",
      "Sergej Milinković-Savić",
      "Nemanja Maksimović",
      "Dušan Tadić",
      "Aleksandar Mitrović",
      "Luka Jović",
      "Filip Kostić",
      "Andrija Živković",
      "Dušan Vlahović",
      "Ivan Ilić",
      "Marko Grujić",
      "Erhan Mašović",
      "Uroš Račić",
    ],
  },
  {
    code: "SVK",
    name: "Eslovaquia",
    flag: "🇸🇰",
    confederation: "UEFA",
    players: [
      "Martin Dúbravka",
      "Peter Pekarík",
      "Milan Škriniar",
      "Norbert Gyömbér",
      "Dávid Hancko",
      "Marek Hamšík",
      "Stanislav Lobotka",
      "Ondrej Duda",
      "Lukáš Haraslín",
      "Ivan Schranz",
      "Robert Boženík",
      "Juraj Kucka",
      "Dávid Strelec",
      "Róbert Mak",
      "Michal Duriš",
      "Tomáš Suslov",
      "Matúš Bero",
      "Jakub Holúbek",
    ],
  },
  {
    code: "SVN",
    name: "Eslovenia",
    flag: "🇸🇮",
    confederation: "UEFA",
    players: [
      "Jan Oblak",
      "Žan Karničnik",
      "Jaka Bijol",
      "Miha Mevlja",
      "Petar Stojanović",
      "Sandi Lovrić",
      "Adam Gnezda Čerin",
      "Timi Max Elšnik",
      "Benjamin Šeško",
      "Andraž Šporar",
      "Josip Iličić",
      "Jon Gorenc Stanković",
      "Jasmin Kurtić",
      "Miha Zajc",
      "Kevin Kampl",
      "Erik Janža",
      "David Brekalo",
      "Žan Celar",
    ],
  },
  {
    code: "AUT",
    name: "Austria",
    flag: "🇦🇹",
    confederation: "UEFA",
    players: [
      "Patrick Pentz",
      "Stefan Lainer",
      "David Alaba",
      "Philipp Lienhart",
      "Maximilian Wöber",
      "Nicolas Seiwald",
      "Florian Grillitsch",
      "Marcel Sabitzer",
      "Christoph Baumgartner",
      "Michael Gregoritsch",
      "Marko Arnautović",
      "Konrad Laimer",
      "Patrick Wimmer",
      "Florian Kainz",
      "Andreas Weimann",
      "Romano Schmid",
      "Dejan Ljubičić",
      "Lukas Klostermann",
    ],
  },
  {
    code: "SUI",
    name: "Suiza",
    flag: "🇨🇭",
    confederation: "UEFA",
    players: [
      "Yann Sommer",
      "Silvan Widmer",
      "Manuel Akanji",
      "Fabian Schär",
      "Ricardo Rodríguez",
      "Granit Xhaka",
      "Remo Freuler",
      "Xherdan Shaqiri",
      "Ruben Vargas",
      "Breel Embolo",
      "Noah Okafor",
      "Michel Aebischer",
      "Denis Zakaria",
      "Dan Ndoye",
      "Zeki Amdouni",
      "Fabian Frei",
      "Steven Zuber",
      "Edimilson Fernandes",
    ],
  },
  {
    code: "SCO",
    name: "Escocia",
    flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    confederation: "UEFA",
    players: [
      "Angus Gunn",
      "Aaron Hickey",
      "Grant Hanley",
      "Scott McKenna",
      "Andrew Robertson",
      "John McGinn",
      "Callum McGregor",
      "Stuart Armstrong",
      "Ryan Christie",
      "Lyndon Dykes",
      "Che Adams",
      "Billy Gilmour",
      "Ryan Jack",
      "Kenny McLean",
      "Lawrence Shankland",
      "Scott McTominay",
      "Ryan Porteous",
      "Josh Doig",
    ],
  },
  {
    code: "UKR",
    name: "Ucrania",
    flag: "🇺🇦",
    confederation: "UEFA",
    players: [
      "Andriy Lunin",
      "Oleksandr Karavaev",
      "Mykola Matviyenko",
      "Illia Zabarnyi",
      "Vitaliy Mykolenko",
      "Mykhailo Mudryk",
      "Mykola Shaparenko",
      "Ruslan Malinovskyi",
      "Andriy Yarmolenko",
      "Roman Yaremchuk",
      "Artem Dovbyk",
      "Viktor Tsygankov",
      "Georgiy Sudakov",
      "Taras Stepanenko",
      "Oleksandr Zinchenko",
      "Oleksandr Syrota",
      "Vladyslav Vanat",
      "Danylo Sikan",
    ],
  },
  // CONCACAF
  {
    code: "USA",
    name: "Estados Unidos",
    flag: "🇺🇸",
    confederation: "CONCACAF",
    players: [
      "Matt Turner",
      "Sergino Dest",
      "Chris Richards",
      "Miles Robinson",
      "Antonee Robinson",
      "Tyler Adams",
      "Weston McKennie",
      "Yunus Musah",
      "Christian Pulisic",
      "Ricardo Pepi",
      "Gio Reyna",
      "Timothy Weah",
      "Brenden Aaronson",
      "Folarin Balogun",
      "Josh Sargent",
      "Reggie Cannon",
      "Malik Tillman",
      "Taylor Booth",
    ],
  },
  {
    code: "MEX",
    name: "México",
    flag: "🇲🇽",
    confederation: "CONCACAF",
    players: [
      "Guillermo Ochoa",
      "Jorge Sánchez",
      "Néstor Araujo",
      "César Montes",
      "Jesús Gallardo",
      "Edson Álvarez",
      "Héctor Herrera",
      "Andrés Guardado",
      "Hirving Lozano",
      "Raúl Jiménez",
      "Henry Martín",
      "Roberto Alvarado",
      "Uriel Antuna",
      "Santiago Giménez",
      "Orbelin Pineda",
      "Carlos Rodríguez",
      "Kevin Álvarez",
      "Germán Berterame",
    ],
  },
  {
    code: "CAN",
    name: "Canadá",
    flag: "🇨🇦",
    confederation: "CONCACAF",
    players: [
      "Maxime Crépeau",
      "Alistair Johnston",
      "Kamal Miller",
      "Steven Vitória",
      "Alphonso Davies",
      "Atiba Hutchinson",
      "Jonathan Osorio",
      "Stephen Eustáquio",
      "Cyle Larin",
      "Jonathan David",
      "Tajon Buchanan",
      "Liam Millar",
      "Junior Hoilett",
      "Mark-Anthony Kaye",
      "Samuel Piette",
      "Richie Laryea",
      "Ismael Koné",
      "Jacob Shaffelburg",
    ],
  },
  {
    code: "PAN",
    name: "Panamá",
    flag: "🇵🇦",
    confederation: "CONCACAF",
    players: [
      "Luis Mejía",
      "Michael Murillo",
      "Harold Cummings",
      "Fidel Escobar",
      "Eric Davis",
      "Édgar Bárcenas",
      "Adalberto Carrasquilla",
      "José Fajardo",
      "Rolando Blackburn",
      "Cecilio Waterman",
      "Ismael Díaz",
      "Roderick Miller",
      "Gabriel Torres",
      "Anibal Godoy",
      "Aníbal Godoy",
      "Alberto Quintero",
      "César Yanis",
      "Tomás Christiansen",
    ],
  },
  {
    code: "CRC",
    name: "Costa Rica",
    flag: "🇨🇷",
    confederation: "CONCACAF",
    players: [
      "Keylor Navas",
      "Juan Pablo Vargas",
      "Francisco Calvo",
      "Bryan Oviedo",
      "Yeltsin Tejeda",
      "Celso Borges",
      "Bryan Ruiz",
      "Joel Campbell",
      "Alajandro Bran",
      "Anthony Contreras",
      "Johan Venegas",
      "Randall Leal",
      "Jewison Bennette",
      "Kendall Waston",
      "Orlando Galo",
      "Gerald Taylor",
      "Álvaro Zamora",
      "Gerson Torres",
    ],
  },
  {
    code: "JAM",
    name: "Jamaica",
    flag: "🇯🇲",
    confederation: "CONCACAF",
    players: [
      "Andre Blake",
      "Damion Lowe",
      "Michail Antonio",
      "Shamar Nicholson",
      "Bobby Reid",
      "Junior Flemmings",
      "Demarai Gray",
      "Ravel Morrison",
      "Leon Bailey",
      "Kasey Palmer",
      "Lamar Walker",
      "Makai Robertson",
      "Ethan Pinnock",
      "Liam Moore",
      "Je-Vaughn Watson",
      "Adrian Mariappa",
      "Chris Burke",
      "Daniel Johnson",
    ],
  },
  // CAF
  {
    code: "MAR",
    name: "Marruecos",
    flag: "🇲🇦",
    confederation: "CAF",
    players: [
      "Yassine Bounou",
      "Achraf Hakimi",
      "Romain Saïss",
      "Nayef Aguerd",
      "Noussair Mazraoui",
      "Sofyan Amrabat",
      "Azzedine Ounahi",
      "Ilias Chair",
      "Hakim Ziyech",
      "Youssef En-Nesyri",
      "Abde Ezzalzouli",
      "Tarik Tissoudali",
      "Selim Amallah",
      "Yahya Attiyat Allah",
      "Sofiane Boufal",
      "Ibrahim Diaz",
      "Jawad El Yamiq",
      "Walid Cheddira",
    ],
  },
  {
    code: "SEN",
    name: "Senegal",
    flag: "🇸🇳",
    confederation: "CAF",
    players: [
      "Édouard Mendy",
      "Youssouf Sabaly",
      "Abdou Diallo",
      "Kalidou Koulibaly",
      "Fodé Ballo-Touré",
      "Idrissa Gueye",
      "Cheikhou Kouyaté",
      "Nampalys Mendy",
      "Sadio Mané",
      "Boulaye Dia",
      "Ismaïla Sarr",
      "Krépin Diatta",
      "Nicolas Jackson",
      "Pape Matar Sarr",
      "Lamine Camara",
      "Formose Mendy",
      "Habib Diallo",
      "Moussa Niakhaté",
    ],
  },
  {
    code: "EGY",
    name: "Egipto",
    flag: "🇪🇬",
    confederation: "CAF",
    players: [
      "Mohamed El-Shenawy",
      "Ahmed Fatouh",
      "Ahmed Hegazi",
      "Omar Gaber",
      "Mohamed Abdel-Shafi",
      "Tarek Hamed",
      "Mohamed Elneny",
      "Mahmoud Hamdi",
      "Mohamed Salah",
      "Mostafa Mohamed",
      "Amr Warda",
      "Omar Marmoush",
      "Ramadan Sobhi",
      "Ahmed Sayed",
      "Trézéguet",
      "Mahmoud Trezeguet",
      "Zizo",
      "Kahraba",
    ],
  },
  {
    code: "NGA",
    name: "Nigeria",
    flag: "🇳🇬",
    confederation: "CAF",
    players: [
      "Francis Uzoho",
      "Ola Aina",
      "Leon Balogun",
      "William Troost-Ekong",
      "Zaidu Sanusi",
      "Wilfred Ndidi",
      "Alex Iwobi",
      "Frank Onyeka",
      "Victor Osimhen",
      "Samuel Chukwueze",
      "Taiwo Awoniyi",
      "Kelechi Iheanacho",
      "Moses Simon",
      "Emmanuel Dennis",
      "Paul Onuachu",
      "Fisayo Dele-Bashiru",
      "Ademola Lookman",
      "Semi Ajayi",
    ],
  },
  {
    code: "CMR",
    name: "Camerún",
    flag: "🇨🇲",
    confederation: "CAF",
    players: [
      "André Onana",
      "Collins Fai",
      "Nicolás Nkoulou",
      "Jean-Charles Castelletto",
      "Harold Moukoudi",
      "André Zambo Anguissa",
      "Stéphane Bahoken",
      "Pierre Kunde",
      "Vincent Aboubakar",
      "Karl Toko Ekambi",
      "Bryan Mbeumo",
      "Georges-Kevin Nkoudou",
      "Gaël Ondoua",
      "Martin Hongla",
      "Jean-Pierre Nsame",
      "Clinton Njie",
      "Christian Bassogog",
      "Arnaud Djoum",
    ],
  },
  {
    code: "MLI",
    name: "Mali",
    flag: "🇲🇱",
    confederation: "CAF",
    players: [
      "Djigui Diarra",
      "Hamari Traoré",
      "Boubacar Kouyaté",
      "Falaye Sacko",
      "Abdoulaye Diaby",
      "Moussa Doumbia",
      "Adama Traoré",
      "Mamadou Coulibaly",
      "El Bilal Touré",
      "Moussa Doumbia",
      "Kamory Doumbia",
      "Amadou Haidara",
      "Mohamed Camara",
      "Ibrahima Koné",
      "Lassine Sinayoko",
      "Yves Bissouma",
      "Sékou Koïta",
      "Aliou Dieng",
    ],
  },
  {
    code: "COD",
    name: "Rep. Dem. Congo",
    flag: "🇨🇩",
    confederation: "CAF",
    players: [
      "Lionel Mpasi",
      "Marcel Tisserand",
      "Chancel Mbemba",
      "Arthur Masuaku",
      "Gaël Kakuta",
      "Yannick Bolasie",
      "Merveille Bito",
      "Silas Wissa",
      "Dieumerci Mbokani",
      "Cédric Bakambu",
      "Theo Bongonda",
      "Jonathan Bolingi",
      "Neeskens Kebano",
      "Samuel Bastien",
      "Joris Kayembe",
      "Wilfried Zaha",
      "Nathan Ilunga",
      "Glody Lilepo",
    ],
  },
  {
    code: "RSA",
    name: "Sudáfrica",
    flag: "🇿🇦",
    confederation: "CAF",
    players: [
      "Ronwen Williams",
      "Teboho Mokoena",
      "Siyabonga Ngezana",
      "Bongani Zungu",
      "Itumeleng Khune",
      "Percy Tau",
      "Themba Zwane",
      "Lebo Mothiba",
      "Fagrie Lakay",
      "Lyle Foster",
      "Bradley Grobler",
      "Evidence Makgopa",
      "Elias Mokwana",
      "Yusuf Maart",
      "Marcelo Allende",
      "Grant Kekana",
      "Nkosinathi Sibisi",
      "Terrence Mashego",
    ],
  },
  {
    code: "TAN",
    name: "Tanzania",
    flag: "🇹🇿",
    confederation: "CAF",
    players: [
      "Aishi Manula",
      "Papy Tshishimbi",
      "Erasto Nyoni",
      "John Bocco",
      "Dickson Job",
      "Mohammed Hussein",
      "Khalid Aucho",
      "Simon Msuva",
      "Mbwana Samatta",
      "Feisal Salum",
      "Shomari Kapombe",
      "Thomas Ulimwengu",
      "Himid Mao",
      "Nizar Khalfan",
      "Charles Zulu",
      "Nadir Haroub",
      "James Kotei",
      "Shiza Kichuya",
    ],
  },
  // AFC
  {
    code: "JPN",
    name: "Japón",
    flag: "🇯🇵",
    confederation: "AFC",
    players: [
      "Shuichi Gonda",
      "Hiroki Sakai",
      "Takehiro Tomiyasu",
      "Maya Yoshida",
      "Yuta Nakayama",
      "Wataru Endō",
      "Hidemasa Morita",
      "Junya Ito",
      "Ritsu Dōan",
      "Takuma Asano",
      "Daichi Kamada",
      "Kaoru Mitoma",
      "Takefusa Kubo",
      "Ayase Ueda",
      "Kou Itakura",
      "Ao Tanaka",
      "Hayao Kawabe",
      "Reo Hatate",
    ],
  },
  {
    code: "KOR",
    name: "Corea del Sur",
    flag: "🇰🇷",
    confederation: "AFC",
    players: [
      "Jo Hyeon-woo",
      "Kim Moon-hwan",
      "Kim Minjae",
      "Kim Young-gwon",
      "Kim Jin-su",
      "Jung Woo-young",
      "Lee Jae-sung",
      "Lee Kang-in",
      "Son Heung-min",
      "Hwang Hee-chan",
      "Hwang Ui-jo",
      "Cho Gue-sung",
      "Na Sang-ho",
      "Bae Jun-ho",
      "Kwon Chang-hoon",
      "Oh Hyeon-gyu",
      "Jeong Sang-bin",
      "Yang Hyun-jun",
    ],
  },
  {
    code: "KSA",
    name: "Arabia Saudita",
    flag: "🇸🇦",
    confederation: "AFC",
    players: [
      "Mohammed Al-Owais",
      "Saud Abdulhamid",
      "Ali Al-Bulaihi",
      "Abdulelah Al-Amri",
      "Yasser Al-Shahrani",
      "Salman Al-Faraj",
      "Mohamed Kanno",
      "Ali Al-Hassan",
      "Firas Al-Buraikan",
      "Salem Al-Dawsari",
      "Haitham Asiri",
      "Abdullah Al-Hamdan",
      "Riyadh Sharahili",
      "Nasser Al-Dawsari",
      "Sami Al-Najei",
      "Hassan Al-Tambakti",
      "Nawaf Al-Abid",
      "Mohammed Al-Burayk",
    ],
  },
  {
    code: "AUS",
    name: "Australia",
    flag: "🇦🇺",
    confederation: "AFC",
    players: [
      "Mathew Ryan",
      "Nathaniel Atkinson",
      "Harry Souttar",
      "Miloš Degenek",
      "Aziz Behich",
      "Jackson Irvine",
      "Riley McGree",
      "Aaron Mooy",
      "Mathew Leckie",
      "Mitchell Duke",
      "Jamie Maclaren",
      "Martin Boyle",
      "Keanu Baccus",
      "Awer Mabil",
      "Jason Cummings",
      "Craig Goodwin",
      "Denis Genreau",
      "Garang Kuol",
    ],
  },
  {
    code: "IRN",
    name: "Irán",
    flag: "🇮🇷",
    confederation: "AFC",
    players: [
      "Alireza Beiranvand",
      "Sadegh Moharrami",
      "Majid Hosseini",
      "Morteza Pouraliganji",
      "Ehsan Hajsafi",
      "Saeid Ezatolahi",
      "Alireza Jahanbakhsh",
      "Mehdi Taremi",
      "Sardar Azmoun",
      "Karim Ansarifard",
      "Ali Karimi",
      "Ramin Rezaeian",
      "Ali Gholizadeh",
      "Saman Ghoddos",
      "Ahmad Noorollahi",
      "Morteza Pouraliganji",
      "Shahriyar Moghanloo",
      "Milad Sarlak",
    ],
  },
  {
    code: "UZB",
    name: "Uzbekistán",
    flag: "🇺🇿",
    confederation: "AFC",
    players: [
      "Utkir Yusupov",
      "Sanjar Tursunov",
      "Eldor Shomurodov",
      "Dostonbek Khamdamov",
      "Abbosbek Fayzullaev",
      "Jaloliddin Masharipov",
      "Otabek Shukurov",
      "Husayn Norchaev",
      "Bobur Abdixoliqov",
      "Sherzod Nasrullayev",
      "Rustam Ashurmatov",
      "Azizbek Turgunboev",
      "Dilshod Vatanshoev",
      "Nodirbek Mirzayev",
      "Sarvarbek Yusupov",
      "Nurbek Khoshimov",
      "Ismoil Ergashev",
      "Muhammadkodir Hamrobekov",
    ],
  },
  {
    code: "JOR",
    name: "Jordania",
    flag: "🇯🇴",
    confederation: "AFC",
    players: [
      "Yazeed Abo Laila",
      "Bahloul Eldin Dodin",
      "Ahmad Ibrahim",
      "Khaled Salameh",
      "Baha' Faisal",
      "Yazan Al-Naimat",
      "Musa Al-Taamari",
      "Hamza Al-Dardour",
      "Ahmed Al-Sarouri",
      "Zaid Al-Naser",
      "Mahmoud Shelbayeh",
      "Ali Olwan",
      "Mohammad Abu Zema",
      "Mousa Suleiman",
      "Abdallah Nasib",
      "Ahmad Harman",
      "Odai Al-Saify",
      "Baha Faisal",
    ],
  },
  {
    code: "IRQ",
    name: "Iraq",
    flag: "🇮🇶",
    confederation: "AFC",
    players: [
      "Jalal Hassan",
      "Ali Adnan",
      "Rebin Sulaka",
      "Saad Natiq",
      "Mustafa Nadhim",
      "Amjed Attwan",
      "Alaa Abbas",
      "Bashar Resan",
      "Aymen Hussein",
      "Mohanad Ali",
      "Osama Rashid",
      "Hussein Saeed",
      "Ahmed Saleh",
      "Hammadi Ahmed",
      "Karrar Jassim",
      "Dhurgham Ismail",
      "Mahdi Kamil",
      "Saif Mahdi",
    ],
  },
  // OFC
  {
    code: "NZL",
    name: "Nueva Zelanda",
    flag: "🇳🇿",
    confederation: "OFC",
    players: [
      "Stefan Marinovic",
      "Winston Reid",
      "Tommy Smith",
      "Liberato Cacace",
      "Bill Tuiloma",
      "Clayton Lewis",
      "Ryan Thomas",
      "Joe Bell",
      "Chris Wood",
      "Callan Elliot",
      "Sarpreet Singh",
      "Kosta Barbarouses",
      "Marko Simonovic",
      "Myer Bevan",
      "Ronan Waitai",
      "Michael Boxall",
      "Matthew Garbett",
      "Elijah Just",
    ],
  },
  // Playoff spots (placeholder)
  {
    code: "PLAY1",
    name: "Playoff Inter-conf. 1",
    flag: "🌍",
    confederation: "PLAYOFF",
    players: [
      "Jugador 1",
      "Jugador 2",
      "Jugador 3",
      "Jugador 4",
      "Jugador 5",
      "Jugador 6",
      "Jugador 7",
      "Jugador 8",
      "Jugador 9",
      "Jugador 10",
      "Jugador 11",
      "Jugador 12",
      "Jugador 13",
      "Jugador 14",
      "Jugador 15",
      "Jugador 16",
      "Jugador 17",
      "Jugador 18",
    ],
  },
  {
    code: "PLAY2",
    name: "Playoff Inter-conf. 2",
    flag: "🌍",
    confederation: "PLAYOFF",
    players: [
      "Jugador 1",
      "Jugador 2",
      "Jugador 3",
      "Jugador 4",
      "Jugador 5",
      "Jugador 6",
      "Jugador 7",
      "Jugador 8",
      "Jugador 9",
      "Jugador 10",
      "Jugador 11",
      "Jugador 12",
      "Jugador 13",
      "Jugador 14",
      "Jugador 15",
      "Jugador 16",
      "Jugador 17",
      "Jugador 18",
    ],
  },
];

async function main() {
  console.log("Seeding database...");

  // Intro section
  const introSection = await prisma.section.upsert({
    where: { code: "INTRO" },
    update: {},
    create: {
      code: "INTRO",
      name: "Introducción",
      type: SectionType.INTRO,
      order: 0,
    },
  });

  let stickerNumber = 1;

  for (const stickerData of INTRO_STICKERS) {
    const sticker = await prisma.sticker.upsert({
      where: { number: stickerNumber },
      update: {},
      create: {
        number: stickerNumber,
        name: stickerData.name,
        type: stickerData.type,
        sectionId: introSection.id,
      },
    });
    await prisma.userSticker.upsert({
      where: { stickerId: sticker.id },
      update: {},
      create: { stickerId: sticker.id, quantity: 0 },
    });
    stickerNumber++;
  }

  // Venues section
  const venuesSection = await prisma.section.upsert({
    where: { code: "VENUES" },
    update: {},
    create: {
      code: "VENUES",
      name: "Estadios Sede",
      type: SectionType.SPECIAL,
      order: 1,
    },
  });

  for (const stickerData of VENUE_STICKERS) {
    const sticker = await prisma.sticker.upsert({
      where: { number: stickerNumber },
      update: {},
      create: {
        number: stickerNumber,
        name: stickerData.name,
        type: stickerData.type,
        sectionId: venuesSection.id,
      },
    });
    await prisma.userSticker.upsert({
      where: { stickerId: sticker.id },
      update: {},
      create: { stickerId: sticker.id, quantity: 0 },
    });
    stickerNumber++;
  }

  // Teams
  for (let i = 0; i < TEAMS.length; i++) {
    const team = TEAMS[i];
    const section = await prisma.section.upsert({
      where: { code: team.code },
      update: {},
      create: {
        code: team.code,
        name: team.name,
        type: SectionType.TEAM,
        flagEmoji: team.flag,
        confederation: team.confederation,
        order: i + 2,
      },
    });

    // Badge sticker
    const badge = await prisma.sticker.upsert({
      where: { number: stickerNumber },
      update: {},
      create: {
        number: stickerNumber,
        name: `Escudo ${team.name}`,
        type: StickerType.BADGE,
        sectionId: section.id,
      },
    });
    await prisma.userSticker.upsert({
      where: { stickerId: badge.id },
      update: {},
      create: { stickerId: badge.id, quantity: 0 },
    });
    stickerNumber++;

    // Team photo
    const teamPhoto = await prisma.sticker.upsert({
      where: { number: stickerNumber },
      update: {},
      create: {
        number: stickerNumber,
        name: `Foto Equipo ${team.name}`,
        type: StickerType.SPECIAL,
        isShiny: true,
        sectionId: section.id,
      },
    });
    await prisma.userSticker.upsert({
      where: { stickerId: teamPhoto.id },
      update: {},
      create: { stickerId: teamPhoto.id, quantity: 0 },
    });
    stickerNumber++;

    // Players
    for (const playerName of team.players) {
      const player = await prisma.sticker.upsert({
        where: { number: stickerNumber },
        update: {},
        create: {
          number: stickerNumber,
          name: playerName,
          type: StickerType.PLAYER,
          sectionId: section.id,
        },
      });
      await prisma.userSticker.upsert({
        where: { stickerId: player.id },
        update: {},
        create: { stickerId: player.id, quantity: 0 },
      });
      stickerNumber++;
    }
  }

  const totalStickers = stickerNumber - 1;
  console.log(
    `✅ Seeded ${totalStickers} stickers across ${TEAMS.length + 2} sections`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
